### ISSUE TITLE
Switching the menu page back while holding the bind button

### ISSUE THREAD

**Issue by tn2009** [OpenI6X/opentx#180]
Is it possible to disable scrolling through the menu with the pots. And add the ability to go to the previous menu page while holding the bind button? 
That would be great!

**Comment by ajjjjjjjj** [comment]
Sure and AFAIK someone is already working on it.

**Comment by tn2009** [comment]
can you do it? :) I think you can do it faster.

**Comment by ajjjjjjjj** [comment]
I was curious how to fix this, so i made this change :)

**Comment by psicho100pro** [comment]
After this modification in modelsel, the iteration skips the second setup tab directly on the flight modes. 
And if you hold BIND immediately on modelsel, the tables will flash back and forth.
To get to it, I have to hold down the BIND button and jump back from flight modes , otherwise I won't get to the second tab.

**Comment by ajjjjjjjj** [comment]
Try now
