### ISSUE TITLE
Make internal module and external ELRS work at the same time

### ISSUE THREAD

**Issue by wimalopaan** [OpenI6X/opentx#394]
Is it possible to enable the internal module and an external ELRS module at the same time?

**Comment by ajjjjjjjj** [comment]
After recent changes yes, but telemetry handling must be  enhanced to support at least switch of currently used telemetry stream. Also logic for switching between modules must be changed because right now it is forced to not alllow both at the same time.
Ideally this should follow (not existing yet) EdgeTX approach.

**Comment by wimalopaan** [comment]
Thanks for the explanation.
Sounds like a reasonable pile of work.
Are there plans to do that?

**Comment by ajjjjjjjj** [comment]
No plans for now.
