### ISSUE TITLE
Use compilation-flag -DCROSSFIRE=OFF to exclude crsf

### ISSUE THREAD

**Issue by wimalopaan** [OpenI6X/opentx#94]
... may this will save some flash space

**Comment by ajjjjjjjj** [comment]
But we use CRSF for ExpressLRS and on other builds FLASH size is not a problem currently or you mean something else?

**Comment by wimalopaan** [comment]
Well, in #90 bin size (flash) is an issue ...

Just make it optional to save space if only AFHDS2A is needed.
Maybe this gives room for other RF protocols on this chipset.

**Comment by ajjjjjjjj** [comment]
We don't have a ready feature that is not enabled on standard builds because of flash size. With disabled CRSF on standard build currently you will gain nothing but loose support for TBS/ExpressLRS modules with display that do not require configuration script.
A7105 can only implement Hubsan X4 protocol besides AFHDS2A, but i doubt that someone will implement it.
